[project]
name = "todo"
version = "0.1.0"
description = "Manage todo under home folder"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.14.1",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "toml>=0.10.2",
]
